### ISSUE TITLE
Question about the CMU-MOSEI database

### ISSUE THREAD

**Issue by mattke0301** [T-Sh/3-Modal-Cross-Bert#1]
Hello, I have some questions about CMU-MOSEI datasets.
Because of the privacy issue, CMU-MOSEI dataset did not provide the raw data. I want to ask that how to get the CMU-MOSEI raw data, thanks.

**Comment by T-Sh** [comment]
Hello, I believe raw data was available at http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/, and I downloaded it from there. For now data is hidden. You can contact me via email tatyana.shimohina23@gmail.com, I'll try to help you and share data.

**Comment by mattke0301** [comment]
Ok, I will contact you via email. Thank you very much!
